// <auto-generated />
using Day4_MVC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day4_MVC.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20250726215636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_DAY2.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptName = "SD"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptName = "UI"
                        },
                        new
                        {
                            DeptId = 3,
                            DeptName = "Mob"
                        },
                        new
                        {
                            DeptId = 4,
                            DeptName = "Network"
                        });
                });

            modelBuilder.Entity("MVC_DAY2.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "cairo",
                            Age = 26,
                            DeptId = 1,
                            Name = "Ahmed"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Alex",
                            Age = 36,
                            DeptId = 2,
                            Name = "Mohamed"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Aswan",
                            Age = 46,
                            DeptId = 3,
                            Name = "Sara"
                        },
                        new
                        {
                            Id = 4,
                            Address = "sqeda",
                            Age = 25,
                            DeptId = 4,
                            Name = "Omar"
                        },
                        new
                        {
                            Id = 5,
                            Address = "magreat",
                            Age = 23,
                            DeptId = 1,
                            Name = "Ali"
                        },
                        new
                        {
                            Id = 6,
                            Address = "NewYourk",
                            Age = 36,
                            DeptId = 2,
                            Name = "Mai"
                        },
                        new
                        {
                            Id = 7,
                            Address = "japan",
                            Age = 49,
                            DeptId = 3,
                            Name = "Ramy"
                        },
                        new
                        {
                            Id = 8,
                            Address = "chena",
                            Age = 18,
                            DeptId = 4,
                            Name = "Hamada"
                        },
                        new
                        {
                            Id = 9,
                            Address = "sadek",
                            Age = 26,
                            DeptId = 1,
                            Name = "Hatem"
                        },
                        new
                        {
                            Id = 10,
                            Address = "newsaty",
                            Age = 25,
                            DeptId = 2,
                            Name = "Osama"
                        });
                });

            modelBuilder.Entity("MVC_DAY2.Models.Student", b =>
                {
                    b.HasOne("MVC_DAY2.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC_DAY2.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
